site_name: BMEVIAUAC00 - Mobil- és webes szoftverek - Webes laborfeladatok
site_author: Tóth Tibor
copyright: Copyright &copy; BME VIK AUT
repo_name: viauac00/web-labor
repo_url: https://github.com/viauac00/web-labor

theme:
  name: material
  language: hu
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb-outline
        name: Váltás sötét témára
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      toggle:
        icon: material/lightbulb
        name: Váltás világos témára
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - search.suggest   
  logo: logo-bme-aut.png
  favicon: favicon.ico

extra_css:
  - extra-material-theme.css

extra:
  generator: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search:
      prebuild_index: true

nav:
  - index.md
  - "Webes Laborok":
      - laborok/08-http/index.md
      - laborok/09-css/index.md
      - laborok/10-bootstrap/index.md
      - laborok/11-js/index.md
      # - laborok/12-jquery/index.md
      # - laborok/13-js-advanced/index.md